version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

    restart: unless-stopped
    networks:
      - museum-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Don't mount node_modules from host if they exist locally
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - museum-net


networks:
  museum-net:
    driver: bridge
